version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "jquery",
    "mongo"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"